// flow-typed signature: db426bd9ca0d6da06fc4b16e78d7d79e
// flow-typed version: <<STUB>>/react-blessed_v^0.2.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-blessed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-blessed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-blessed/dist/fiber/devtools' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/fiber/events' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/fiber/fiber' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/fiber/index' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/index' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/shared/solveClass' {
  declare module.exports: any;
}

declare module 'react-blessed/dist/shared/update' {
  declare module.exports: any;
}

declare module 'react-blessed/run' {
  declare module.exports: any;
}

declare module 'react-blessed/src/fiber/devtools' {
  declare module.exports: any;
}

declare module 'react-blessed/src/fiber/events' {
  declare module.exports: any;
}

declare module 'react-blessed/src/fiber/fiber' {
  declare module.exports: any;
}

declare module 'react-blessed/src/fiber/index' {
  declare module.exports: any;
}

declare module 'react-blessed/src/index' {
  declare module.exports: any;
}

declare module 'react-blessed/src/shared/solveClass' {
  declare module.exports: any;
}

declare module 'react-blessed/src/shared/update' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-blessed/dist/fiber/devtools.js' {
  declare module.exports: $Exports<'react-blessed/dist/fiber/devtools'>;
}
declare module 'react-blessed/dist/fiber/events.js' {
  declare module.exports: $Exports<'react-blessed/dist/fiber/events'>;
}
declare module 'react-blessed/dist/fiber/fiber.js' {
  declare module.exports: $Exports<'react-blessed/dist/fiber/fiber'>;
}
declare module 'react-blessed/dist/fiber/index.js' {
  declare module.exports: $Exports<'react-blessed/dist/fiber/index'>;
}
declare module 'react-blessed/dist/index.js' {
  declare module.exports: $Exports<'react-blessed/dist/index'>;
}
declare module 'react-blessed/dist/shared/solveClass.js' {
  declare module.exports: $Exports<'react-blessed/dist/shared/solveClass'>;
}
declare module 'react-blessed/dist/shared/update.js' {
  declare module.exports: $Exports<'react-blessed/dist/shared/update'>;
}
declare module 'react-blessed/run.js' {
  declare module.exports: $Exports<'react-blessed/run'>;
}
declare module 'react-blessed/src/fiber/devtools.js' {
  declare module.exports: $Exports<'react-blessed/src/fiber/devtools'>;
}
declare module 'react-blessed/src/fiber/events.js' {
  declare module.exports: $Exports<'react-blessed/src/fiber/events'>;
}
declare module 'react-blessed/src/fiber/fiber.js' {
  declare module.exports: $Exports<'react-blessed/src/fiber/fiber'>;
}
declare module 'react-blessed/src/fiber/index.js' {
  declare module.exports: $Exports<'react-blessed/src/fiber/index'>;
}
declare module 'react-blessed/src/index.js' {
  declare module.exports: $Exports<'react-blessed/src/index'>;
}
declare module 'react-blessed/src/shared/solveClass.js' {
  declare module.exports: $Exports<'react-blessed/src/shared/solveClass'>;
}
declare module 'react-blessed/src/shared/update.js' {
  declare module.exports: $Exports<'react-blessed/src/shared/update'>;
}
